config/routes.rb
Rails.application.routes.draw do
  resources :user_accounts
  resources :boards
  resources :matches
  devise_for :users
  resources :tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root 'matches#index'
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :user
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  before_action :set_user_account, only: [:show, :edit, :update, :destroy]

  # GET /user_accounts
  # GET /user_accounts.json
  def index
    @user_accounts = UserAccount.all
  end

  # GET /user_accounts/1
  # GET /user_accounts/1.json
  def show
  end

  # GET /user_accounts/new
  def new
    @user_account = UserAccount.new
  end

  # GET /user_accounts/1/edit
  def edit
  end

  # POST /user_accounts
  # POST /user_accounts.json
  def create
    @user_account = UserAccount.new(user_account_params)

    respond_to do |format|
      if @user_account.save
        format.html { redirect_to @user_account, notice: 'User account was successfully created.' }
        format.json { render :show, status: :created, location: @user_account }
      else
        format.html { render :new }
        format.json { render json: @user_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_accounts/1
  # PATCH/PUT /user_accounts/1.json
  def update
    respond_to do |format|
      if @user_account.update(user_account_params)
        format.html { redirect_to @user_account, notice: 'User account was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_account }
      else
        format.html { render :edit }
        format.json { render json: @user_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_accounts/1
  # DELETE /user_accounts/1.json
  def destroy
    @user_account.destroy
    respond_to do |format|
      format.html { redirect_to user_accounts_url, notice: 'User account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_account
      @user_account = UserAccount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_account_params
      params.require(:user_account).permit(:bank_name, :acount_number, :cash, :user_id)
    end
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/views/user_accounts/_form.html.erb
<%= form_with(model: user_account, local: true) do |form| %>
  <% if user_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_account.errors.count, "error") %> prohibited this user_account from being saved:</h2>

      <ul>
      <% user_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bank_name %>
    <%= form.text_field :bank_name %>
  </div>

  <div class="field">
    <%= form.label :acount_number %>
    <%= form.text_field :acount_number %>
  </div>

  <div class="field">
    <%= form.label :cash %>
    <%= form.number_field :cash %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_accounts/edit.html.erb
<h1>Editing User Account</h1>

<%= render 'form', user_account: @user_account %>

<%= link_to 'Show', @user_account %> |
<%= link_to 'Back', user_accounts_path %>

app/views/user_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>연동 계좌</h1>

<table>
  <thead>
    <tr>
      <th>은행명</th>
      <th>계좌번호</th>
      <th>잔고</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_accounts.each do |user_account| %>
      <tr>
        <td><%= user_account.bank_name %></td>
        <td><%= user_account.acount_number %></td>
        <td><%= user_account.cash %></td>
        <td><%= user_account.user.email %></td>
        <td><%= link_to 'Show', user_account %></td>
        <td><%= link_to 'Edit', edit_user_account_path(user_account) %></td>
        <td><%= link_to 'Destroy', user_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Account', new_user_account_path %>
<%= link_to '경기표', matches_path %>
<%= link_to '시청목록', boards_path %>

app/views/user_accounts/new.html.erb
<h1>New User Account</h1>

<%= render 'form', user_account: @user_account %>

<%= link_to 'Back', user_accounts_path %>

app/views/user_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank name:</strong>
  <%= @user_account.bank_name %>
</p>

<p>
  <strong>Acount number:</strong>
  <%= @user_account.acount_number %>
</p>

<p>
  <strong>Cash:</strong>
  <%= @user_account.cash %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_account.user %>
</p>

<%= link_to 'Edit', edit_user_account_path(@user_account) %> |
<%= link_to 'Back', user_accounts_path %>